language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Hurl+tvV1EFQBt+h/1gJW2/DvXkIRoDCogVAmpDY1AHaF1zK7gtJp1Pb8xnjNlaCRzH9HfKn4vEQSYPmeVGJCUuQ+x0P5CQ62UxItZqe24aWAoLCUUm3R7clbY3MnMrZRn9RrgRAWq2jyuOcLf9mfISpdPu7Hk/PqxzzylTcwZoDcKqYLvV49W3yHoAwnx7KCk33DD/Yuxw4f+j5Q/gK5KP15w0jyGPJAtLyTuTlNJqpV3cFL7ms7g3r3F2hZps8M+Ckld4OEXXfkUf1A6gcZA6EYoW7Hz60MS6Clz9Um8AY9NsEybMDIOmaNVxPWY5ZkZMxzRp6ZfmN8eRkYrPq3jC5pHBGrA18kie/XadYB5sZuyfB7jS7Mts8kkn8X0Cqk6HZuPQsKd7VBoGomQ/7t52s+ZvOjtzKeA6PFg130eWPyeNT/4b0o351HU1ZVq+e4TVnfnd4LXl4CxgtZZR9xMKVoOyLZvnnzqR9LBjJCRqto4zG8STbrjAe+8tPR9XX/5jX/2sXHFvl1MOPtnWyc44Nmq7ZDkU4dYHbRhclgdGUQwzRIminQPmurk3j9+5qXDl8IIYPtAJ9rbQUvtwAFIZ62gq2e341lmegQVNk4qEOAant6mj7MN2rWjP0FVFVflm3KOp1Lv1nT9GwfxgNNxwlKAueJsC+3qxPYVGngeo=
  app: salty-castle-32216
  on:
    repo: marissafaulkner/Node-Capstone-Project
